name: Website Change Monitor

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-monitor-script:
    runs-on: ubuntu-latest

    steps:
      - name: Download last hash artifact
        uses: actions/download-artifact@v4
        with:
          name: last-hash
          path: state
        continue-on-error: true

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # ---- NEW STEP TO INSTALL GOOGLE CHROME ----
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          # Also install the correct webdriver for Chrome
          pip install webdriver-manager

      - name: Run website monitor
        env:
          WEBSITE_URL: ${{ secrets.WEBSITE_URL }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python website_monitor.py
        
      - name: Upload new hash as artifact
        uses: actions/upload-artifact@v4
        with:
          name: last-hash
          path: state/last_hash.txt
